POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{ "login": "adam", "nickname": "adam", "password_hash": "Pass1234!"}

###

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json Authorization: token xxx