# Generated by Django 4.1.6 on 2023-02-27 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField()),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('xp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(default=0)),
                ('answerd_questions', models.IntegerField(default=0)),
                ('right_answers', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(null=True)),
                ('music_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_api.musiclesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NI', 'Note idetification')], max_length=2)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='musiclesson',
            name='questions',
            field=models.ManyToManyField(to='lessons_api.question'),
        ),
        migrations.AddField(
            model_name='musiclesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
