# Generated by Django 4.1.6 on 2023-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiclesson',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_json',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
