# Generated by Django 4.2.7 on 2023-11-06 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons_api", "0002_musiclesson_name_question_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="login",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="password_hash",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name="PianoClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("lessons", models.ManyToManyField(to="lessons_api.musiclesson")),
                ("students", models.ManyToManyField(to="lessons_api.student")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studentlesson",
            name="class_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessons_api.pianoclass",
            ),
        ),
    ]
