# Generated by Django 4.2.9 on 2024-04-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_api', '0007_student_teacher_studentlesson_date_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar_id',
            field=models.IntegerField(default=0),
        ),
    ]
