# Generated by Django 4.2.9 on 2024-04-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_api', '0008_student_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlesson',
            name='time_finished',
            field=models.DateTimeField(null=True),
        ),
    ]
