# Generated by Django 4.2.9 on 2024-04-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_api', '0010_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclesson',
            name='slug',
            field=models.SlugField(default='slug_tmp', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
