name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'please deploy')
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd Pianano
          git pull
          echo "DEBUG=False" > .env
          echo "ALLOWED_HOSTS=.kindejak.cz" >> .env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET }}" >> .env
          sudo docker-compose up -d --build
          ls -al
